# Generated by Django 3.2.10 on 2023-08-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0003_cartdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartdb',
        ),
    ]
