# Generated by Django 3.2.10 on 2023-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0006_servicebookdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmntdb',
            name='hospitalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
