# Generated by Django 3.2.10 on 2023-07-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_doctordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='hospitalname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
