# Generated by Django 3.2.10 on 2023-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctordb_hospitalname'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(blank=True, max_length=100, null=True)),
                ('rates', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
