# Generated by Django 3.2.10 on 2023-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_gallerydb'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='serv_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
