# Generated by Django 3.2.10 on 2023-07-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_servicedb_serv_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedb',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
