# Generated by Django 3.2.10 on 2023-07-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_servicedb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(blank=True, max_length=100, null=True)),
                ('deptphoto', models.ImageField(blank=True, null=True, upload_to='pic')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
