# Generated by Django 3.2.10 on 2023-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_deptdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdb',
            name='description2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
