# Generated by Django 3.2.10 on 2023-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_deptdb_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordb',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
