# Generated by Django 3.2.10 on 2023-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_doctordb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptdb',
            name='feature1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deptdb',
            name='feature2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deptdb',
            name='features3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deptdb',
            name='features4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
