# Generated by Django 3.2.10 on 2023-08-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20230809_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedeldb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('patientname', models.CharField(blank=True, max_length=100, null=True)),
                ('Mobilenumber', models.IntegerField(blank=True, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
