# Generated by Django 3.2.10 on 2023-08-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_savedeldb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedeldb',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedeldb',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
