# Generated by Django 3.2.10 on 2023-08-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_auto_20230812_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedelappointmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospitalname', models.CharField(blank=True, max_length=100, null=True)),
                ('DoctorName', models.CharField(blank=True, max_length=100, null=True)),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.CharField(blank=True, max_length=100, null=True)),
                ('patientname', models.CharField(blank=True, max_length=100, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
